common:
  env: prd
  replicas: 2
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx5000m -Xss512k -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:ActiveProcessorCount=2
        -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8

ingress:
  domainName: -gcp2.entur.io

netex:
  publish:
    enabled: false
  publication:
    internal:
      bucket: ror-nisaba-exchange-varelager-production
gcp:
  blobstoreProjectId: entur-ror-prod
  nisabaPubsubProjectId: ent-nisaba-prd
  mardukPubsubProjectId: ent-marduk-prd

  marduk:
    bucketName: marduk-production

  nisaba:
    bucketName: nisaba-production
    exchangeBucketName: ror-nisaba-exchange-production


kafka:
  brokers: entur-kafka-prod-int-entur-prod.aivencloud.com:14019
  registry: https://entur-kafka-prod-int-entur-prod.aivencloud.com:14009
  topic:
    event: rutedata-dataset-import-event-production
    idempotent: rutedata-dataset-import-event-idempotent-repo-production

