common:
  env: tst
  replicas: 2
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx5000m -Xss512k -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:ActiveProcessorCount=2
        -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote.port=9999  -Dcom.sun.management.jmxremote.rmi.port=9998 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1

ingress:
  domainName: -gcp2.staging.entur.io

netex:
  publish:
    enabled: false
  publication:
    internal:
      bucket: ror-nisaba-exchange-varelager-test

gcp:
  blobstoreProjectId: entur-ror-test
  nisabaPubsubProjectId: ent-nisaba-tst
  mardukPubsubProjectId: ent-marduk-tst

  marduk:
    bucketName: marduk-test

  nisaba:
    bucketName: nisaba-test
    exchangeBucketName: ror-nisaba-exchange-test

kafka:
  brokers: entur-kafka-test-int-entur-test.aivencloud.com:11877
  registry: https://entur-kafka-test-int-entur-test.aivencloud.com:11867
  topic:
    event: rutedata-dataset-import-event-staging
    idempotent: rutedata-dataset-import-event-idempotent-repo-staging
