common:
  env: prd
  replicas: 2

ingress:
  domainName: -gcp2.entur.io

netex:
  publish:
    enabled: true
  publication:
    internal:
      bucket: ror-nisaba-exchange-varelager-production
gcp:
  blobstoreProjectId: entur-ror-prod
  nisabaPubsubProjectId: ent-nisaba-prd
  mardukPubsubProjectId: ent-marduk-prd

  marduk:
    bucketName: marduk-production

  nisaba:
    bucketName: ror-nisaba-production
    exchangeBucketName: ror-nisaba-exchange-production


kafka:
  brokers: entur-kafka-prod-int-entur-prod.aivencloud.com:14019
  registry: https://entur-kafka-prod-int-entur-prod.aivencloud.com:14009
  topic:
    event: rutedata-dataset-import-event-production
    idempotent: rutedata-dataset-import-event-idempotent-repo-production
    common: rutedata-dataset-import-common-production
    servicejourney: rutedata-dataset-import-service-journey-production
