common:
  app: nisaba
  shortname: nisaba
  team: ror
  ingress:
    enabled: false
  service:
    externalPort: 8080
    internalPort: 8080
  container:
    labels: { customLogRetention: enabled }
    forceReplicas: 2
    image: ${artifact.metadata.image}
    cpu: 1
    memory: 1800
    cpuLimit: 1000m
    memoryLimit: 2000
    envFrom:
      - secretRef:
            name: ror-nisba-secrets
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: nisaba-application
        name: application-config
  postgres:
    enabled: false
  configmap:
    data:
      JDK_JAVA_OPTIONS:  -server -Xmx1600m -Xss512k -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40
        -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true