apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nisaba-service-account
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nisaba.common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nisaba-service-account
subjects:
  - kind: ServiceAccount
    name: application
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nisaba-service-account
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nisaba.common.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["nisaba-leaders-lock-on-netex-export-notification-queue-route"]
    verbs: ["create", "get", "patch", "update", "list"]
