apiVersion: v2
# template for application version, the actual version number is set at build time
appVersion: "0.1.99.1"
description: Backend integration
name: nisaba
version: 0.1.0
keywords:
  - nisaba
sources:
  - https://github.com/entur/nisaba
maintainers:
  - name: 'team-ror'
    email: team.rutedata@entur.org
dependencies:
  - name: common
    version: 1.17.5
    repository: "https://entur.github.io/helm-charts"

