env: dev
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev
  bucketName: marduk-dev

monitoringEnabled: true

kafka:
  brokers: bootstrap.test-int.kafka.entur.io:9095
  registry: http://schema-registry.test-int.kafka.entur.io:8001
  topic:
    event: rutedata-dataset-import-event-dev
    idempotent: rutedata-dataset-import-event-idempotent-repo-dev
    common: rutedata-dataset-import-common-dev
    servicejourney: rutedata-dataset-import-servicejourney-dev
