env: dev
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev
  bucketName: marduk-dev

monitoringEnabled: true

kafka:
  brokers: bootstrap.test-int.kafka.entur.io:9095
  topic:
    event: rutedata-dataset-import-event-dev
    idempotent: rutedata-dataset-import-event-idempotent-repo-dev

