env: production
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod
  bucketName: marduk-production

monitoringEnabled: false

kafka:
  brokers: localhost:9092
  topic:
    event: ror-netex-import-event-production
    idempotent: ror-netex-import-event-idempotent-repo-production
