env: production
replicas: 6

gcp:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod
  bucketName: marduk-production
  exchangeBucketName: ror-marduk-exchange-production
  nisaba:
    bucketName: nisaba-production

monitoringEnabled: false

kafka:
  brokers: bootstrap.prod-int.kafka.entur.io:9095
  registry: http://schema-registry.prod-int.kafka.entur.io:8001
  topic:
    event: rutedata-dataset-import-event-production
    idempotent: rutedata-dataset-import-event-idempotent-repo-production
    common: rutedata-dataset-import-common-production
    servicejourney: rutedata-dataset-import-service-journey-production
