env: production
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod
  bucketName: marduk-production

monitoringEnabled: false

kafka:
  brokers: bootstrap.prod-int.kafka.entur.io:9095
  registry: http://schema-registry.prod-int.kafka.entur.io:8001
  topic:
    event: rutedata-dataset-import-event-production
    idempotent: rutedata-dataset-import-event-idempotent-repo-production
    common: rutedata-dataset-import-common-production
    servicejourney: rutedata-dataset-import-servicejourney-production
