env: staging
replicas: 6

gcp:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test
  bucketName: marduk-test
  exchangeBucketName: ror-marduk-exchange-test
  nisaba:
    bucketName: nisaba-test

monitoringEnabled: true

kafka:
  brokers: bootstrap.test-int.kafka.entur.io:9095
  registry: http://schema-registry.test-int.kafka.entur.io:8001
  topic:
    event: rutedata-dataset-import-event-staging
    idempotent: rutedata-dataset-import-event-idempotent-repo-staging
    common: rutedata-dataset-import-common-staging
    servicejourney: rutedata-dataset-import-service-journey-staging
