env: staging
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test
  bucketName: marduk-test

monitoringEnabled: true

kafka:
  brokers: localhost:9092
  topic:
    event: rutedata-dataset-import-event-staging
    idempotent: rutedata-dataset-import-event-idempotent-repo-staging