image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: 1500m
  memLimit: 5000Mi
  cpuRequest: 1000m
  memRequest: 4000Mi
  xmx: 3g
