image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: 1000m
  memLimit: 1600Mi
  cpuRequest: 1000m
  memRequest: 1400Mi
  xmx: 1200m
